### ISSUE TITLE
Domain decomposition using layout.exchange

### ISSUE THREAD

**Issue by sigbjobo** [sigbjobo/hPF_MD_PMESH#4]
When using option domain_decomp=True, the code runs, but does not conserve the energy (energy.dat).

Possible reasons:
1. layouts=[None,None], which means paint command with layout=None # Could not be consistent with how pmesh works.

Working code:
                      E
0.000000        2093.218912     2093.218912     0.000000        0.000000        0.000000        0.000000      0.000000
0.049500        2093.218858     2091.785618     1.433240        0.011486        0.000000        0.000000      0.000000

Not working code:
                        E  
0.000000        2606.411707     2606.411707     0.000000        0.000000        0.000000        0.000000      0.000000
0.049500        2608.983658     2607.867166     1.116492        0.008948        0.000000        0.000000      0.000000

**Comment by rainwoodman** [comment]
Layout = None would mean only painting using particles local on this processor. 

As the spatial distribution of particles usually mismatch that of the PM local mesh, the mass / energy is not conserved.

**Comment by sigbjobo** [comment]
Maybe I have a critical misunderstanding, but once the particles have been through decompose (e.g. r=layout.decompose(r)), the particles should match the PM local mesh, and layout should be set to None.

**Comment by rainwoodman** [comment]
That's almost right. However, the particles still have a smoothing window
with a support (in case of CIC, the default, the window is 1 mesh size).
So paint/readout without decompose creates gaps along the pm domain edges.

**Comment by sigbjobo** [comment]
Okey, but in terms of altering the code, do you have any ideas?

**Comment by sigbjobo** [comment]
Okay, I think I managed. What I do now is:
1. I exchange particles by a single layout, smoothing=0.
2. Then I make a new layout for the exchanged positions.
[https://github.com/sigbjobo/hPF_MD_PMESH/blob/63bee14ad6a71c2e7ef3890611648e5803b5f96e/main.py#L272-L285](lines changed)

**Comment by rainwoodman** [comment]
Yes I was going to say that the code looked about right. I'll send in a PR
for some code-refactoring.

**Comment by sigbjobo** [comment]
Thank you for your pull request! The domain decomposition is now working, and I therefore close this issue.
